# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'mainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_MainPage(QMainWindow):
    # 변수 정의
    btn_selDes = None
    btn_manDriving = None
    btn_emrCall = None
    
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow_mainPage")
        MainWindow.resize(1024, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 600))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1021, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.layout_title = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.layout_title.setContentsMargins(0, 0, 0, 0)
        self.layout_title.setObjectName("layout_title")
        self.title = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("text-align: center;")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.layout_title.addWidget(self.title)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 119, 1021, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout_contents = QtWidgets.QHBoxLayout(self.verticalLayoutWidget)
        self.layout_contents.setContentsMargins(0, 0, 0, 0)
        self.layout_contents.setObjectName("layout_contents")
        spacerItem = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.layout_contents.addItem(spacerItem)
        self.layout_btns = QtWidgets.QVBoxLayout()
        self.layout_btns.setObjectName("layout_btns")
        Ui_MainPage.btn_selDes = QtWidgets.QPushButton(self.verticalLayoutWidget)
        Ui_MainPage.btn_selDes.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_MainPage.btn_selDes.sizePolicy().hasHeightForWidth())
        Ui_MainPage.btn_selDes.setSizePolicy(sizePolicy)
        Ui_MainPage.btn_selDes.setMinimumSize(QtCore.QSize(400, 100))
        Ui_MainPage.btn_selDes.setMaximumSize(QtCore.QSize(400, 75))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        Ui_MainPage.btn_selDes.setFont(font)
        Ui_MainPage.btn_selDes.setLayoutDirection(QtCore.Qt.LeftToRight)
        Ui_MainPage.btn_selDes.setStyleSheet("background-color: #cfe3ac;\n"
                                      "margin: 5px;\n"
                                      "padding: 10px;")
        Ui_MainPage.btn_selDes.setObjectName("btn_selDes")
        self.layout_btns.addWidget(Ui_MainPage.btn_selDes, 0, QtCore.Qt.AlignVCenter)
        Ui_MainPage.btn_manDriving = QtWidgets.QPushButton(self.verticalLayoutWidget)
        Ui_MainPage.btn_manDriving.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_MainPage.btn_manDriving.sizePolicy().hasHeightForWidth())
        Ui_MainPage.btn_manDriving.setSizePolicy(sizePolicy)
        Ui_MainPage.btn_manDriving.setMinimumSize(QtCore.QSize(400, 100))
        Ui_MainPage.btn_manDriving.setMaximumSize(QtCore.QSize(400, 75))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        Ui_MainPage.btn_manDriving.setFont(font)
        Ui_MainPage.btn_manDriving.setLayoutDirection(QtCore.Qt.LeftToRight)
        Ui_MainPage.btn_manDriving.setStyleSheet("background-color: #cfe3ac;\n"
                                          "margin: 5px;\n"
                                          "padding: 10px;")
        Ui_MainPage.btn_manDriving.setObjectName("btn_manDriving")
        self.layout_btns.addWidget(Ui_MainPage.btn_manDriving, 0, QtCore.Qt.AlignVCenter)
        Ui_MainPage.btn_emrCall = QtWidgets.QPushButton(self.verticalLayoutWidget)
        Ui_MainPage.btn_emrCall.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_MainPage.btn_emrCall.sizePolicy().hasHeightForWidth())
        Ui_MainPage.btn_emrCall.setSizePolicy(sizePolicy)
        Ui_MainPage.btn_emrCall.setMinimumSize(QtCore.QSize(400, 100))
        Ui_MainPage.btn_emrCall.setMaximumSize(QtCore.QSize(400, 75))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        Ui_MainPage.btn_emrCall.setFont(font)
        Ui_MainPage.btn_emrCall.setLayoutDirection(QtCore.Qt.LeftToRight)
        Ui_MainPage.btn_emrCall.setStyleSheet("background-color: #cfe3ac;\n"
                                       "margin: 5px;\n"
                                       "padding: 10px;")
        Ui_MainPage.btn_emrCall.setObjectName("btn_emrCall")
        self.layout_btns.addWidget(Ui_MainPage.btn_emrCall, 0, QtCore.Qt.AlignVCenter)
        self.layout_contents.addLayout(self.layout_btns)
        spacerItem1 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.layout_contents.addItem(spacerItem1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 520, 1021, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.layout_bottom = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.layout_bottom.setContentsMargins(0, 0, 0, 0)
        self.layout_bottom.setObjectName("layout_bottom")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "홈"))
        Ui_MainPage.btn_selDes.setText(_translate("MainWindow", "목적지 설정"))
        Ui_MainPage.btn_manDriving.setText(_translate("MainWindow", "수동주행"))
        Ui_MainPage.btn_emrCall.setText(_translate("MainWindow", "긴급호출"))


# if __name__ == "__main__":
#     # QApplication : 프로그램을 실행시켜주는 클래스
#     app = QApplication(sys.argv)
#
#     # WindowClass의 인스턴스 생성
#     myWindow = Ui_MainPage()
#
#     # 프로그램 화면을 보여주는 코드
#     myWindow.show()
#
#     # 프로그램을 이벤트루프로 진입시키는(프로그램을 작동시키는) 코드
#     app.exec_()
